version: '2'

services:
    nginx:
        image: nginx:1.13.5
        ports:
            - 8002:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html
        links:
           # - redis
            - mysql

    mysql:
        image: mysql:8.0.3
        ports:
            - 3305:3306
        volumes:
            - ~/.backup/mysql/mws:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=mws"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8086:80
        #links:
        #    - mysql
        environment:
            PMA_HOST: mysql

    #redis:
     #   image: redis:3.2.10
      #  container_name: redis
       # volumes:
        #    - ~/.backup/redis/ggpayapi:/data



